### PR TITLE
Fix/dialog

### LINKED ISSUE #29: Overeager validation
For blueprints without custom add fields the default dialog is shows but with instant validation:

grafik

Validation should only kick in after the user entered content or after submitting the form.

### PR DESCRIPTION
**Pull request by nilshoerrmann**
This commit adapts the dialog UI to the Panel’s current default layout.
It also makes sure fields are not validated on load and that the submit button is correctly labeled.

Fixes #29

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -27,7 +27,7 @@ const PAGE_CREATE_DIALOG = {
       section: null,
       templates: [],
       template: '',
-      page: {},
+      page: this.emptyForm(),
```
Comment (steirico) [inline index.js:30]: I'd like to stick with:

```suggestion
      page: {},
```

Line 74 and follow are dedicated to populate the `page` object according to the fields. But [`emptyForm()`](https://github.com/getkirby/kirby/blob/7525553b8d9976d6ed08b702f62fc3d368116777/panel/src/components/Dialogs/PageCreateDialog.vue#L66-L72) populates the properties `title`, `slug` and `template` only.

Comment (nilshoerrmann) [reply index.js]: I just reverted that change.

**Comment by steirico** [comment]
For line 163 and follow I would suggest:

```js
if(form) {
        form.novalidate = false;
        errors = form.$refs.fields.errors;
        invalid = true;
....
```

This re-enables form validation. Hence, the red indicators on invalid fields will be shown after hitting the submit button.

**Comment by nilshoerrmann** [comment]
Changed that, too.

**Comment by steirico** [comment]
LGTM!

**Comment by nilshoerrmann** [comment]
Great, thank you!
